--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/5/2023 2:00:10 AM
-- Server version: 8.0.32
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE hospital_2;

--
-- Drop table `error`
--
DROP TABLE IF EXISTS error;

--
-- Drop table `lab_test`
--
DROP TABLE IF EXISTS lab_test;

--
-- Drop table `op_data`
--
DROP TABLE IF EXISTS op_data;

--
-- Drop table `op`
--
DROP TABLE IF EXISTS op;

--
-- Drop table `radiology_test`
--
DROP TABLE IF EXISTS radiology_test;

--
-- Drop table `trt_medication`
--
DROP TABLE IF EXISTS trt_medication;

--
-- Drop table `case_dia`
--
DROP TABLE IF EXISTS case_dia;

--
-- Drop table `patient_appt`
--
DROP TABLE IF EXISTS patient_appt;

--
-- Drop table `clinicss_skd`
--
DROP TABLE IF EXISTS clinicss_skd;

--
-- Drop table `emerg_skd_call_jct`
--
DROP TABLE IF EXISTS emerg_skd_call_jct;

--
-- Drop table `emerg_skd`
--
DROP TABLE IF EXISTS emerg_skd;

--
-- Drop table `icu_doctor_visit`
--
DROP TABLE IF EXISTS icu_doctor_visit;

--
-- Drop table `doctor`
--
DROP TABLE IF EXISTS doctor;

--
-- Drop table `authtoken`
--
DROP TABLE IF EXISTS authtoken;

--
-- Drop table `doctor_call`
--
DROP TABLE IF EXISTS doctor_call;

--
-- Drop table `er_adm_and_dc`
--
DROP TABLE IF EXISTS er_adm_and_dc;

--
-- Drop table `icu_relative_visit`
--
DROP TABLE IF EXISTS icu_relative_visit;

--
-- Drop table `icu_follow_up_sheet`
--
DROP TABLE IF EXISTS icu_follow_up_sheet;

--
-- Drop table `icu_adm_dc`
--
DROP TABLE IF EXISTS icu_adm_dc;

--
-- Drop table `old_history`
--
DROP TABLE IF EXISTS old_history;

--
-- Drop table `patient`
--
DROP TABLE IF EXISTS patient;

--
-- Drop table `token`
--
DROP TABLE IF EXISTS token;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE hospital_2;

--
-- Create table `user`
--
CREATE TABLE user (
  User_Id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Role VARCHAR(255) DEFAULT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  PRIMARY KEY (User_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `username` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX username(username);

--
-- Create index `email` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX email(Email);

--
-- Create table `token`
--
CREATE TABLE token (
  id INT NOT NULL AUTO_INCREMENT,
  token VARCHAR(255) NOT NULL,
  User_Id INT NOT NULL,
  type ENUM('refresh','resetPassword','verifyEmail') NOT NULL,
  expires DATETIME NOT NULL,
  blacklisted TINYINT(1) DEFAULT 0,
  createdAt DATETIME NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `token` on table `token`
--
ALTER TABLE token 
  ADD UNIQUE INDEX token(token);

--
-- Create foreign key
--
ALTER TABLE token 
  ADD CONSTRAINT token_user FOREIGN KEY (User_Id)
    REFERENCES user(User_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `patient`
--
CREATE TABLE patient (
  Patient_Id INT NOT NULL AUTO_INCREMENT,
  User_Id INT NOT NULL,
  National_Id CHAR(14) NOT NULL,
  Full_Name VARCHAR(600) DEFAULT NULL COMMENT 'Composite attribute',
  First_Name VARCHAR(150) NOT NULL,
  Second_Name VARCHAR(150) NOT NULL,
  Third_Name VARCHAR(150) NOT NULL,
  Last_Name VARCHAR(150) NOT NULL,
  Birth_Date DATE NOT NULL,
  Age INT DEFAULT NULL,
  Religion INT DEFAULT NULL COMMENT 'o for Muslem ,\\\\\\\\n1 for Christian\\\\\\\\n2 for Jewish',
  Gender INT NOT NULL COMMENT '0 represent Males ,\\\\n1 represent Females',
  Marital_Status INT DEFAULT NULL COMMENT '0 for  Single ,\\\\\\\\n1 for Married \\\\\\\\n2 for Divorced \\\\\\\\n3 for WIdower',
  Nationality INT NOT NULL COMMENT 'Reference from a List of all Nationalities',
  Blood_Type INT DEFAULT NULL COMMENT '0 for  A+ ,\\\\n1 for A- ,\\\\n2 for B+ ,\\\\n3 for B- ,\\\\n4 for O+ ,\\\\n5 for O- ,\\\\n6 for AB+ ,\\\\n7 for AB- ,',
  Address VARCHAR(255) DEFAULT ' ',
  Governorate VARCHAR(50) DEFAULT NULL,
  District VARCHAR(50) DEFAULT NULL,
  Street VARCHAR(50) DEFAULT NULL,
  Building_Number VARCHAR(3) DEFAULT NULL,
  Birth_Place VARCHAR(100) DEFAULT NULL COMMENT 'Composite attribute',
  Birth_Place_Country VARCHAR(50) DEFAULT NULL COMMENT 'Governate',
  Bith_Place_City VARCHAR(50) DEFAULT NULL,
  Phone_Number VARCHAR(50) NOT NULL,
  Height DECIMAL(5, 2) DEFAULT NULL COMMENT 'Height in cm',
  Weight DECIMAL(5, 2) DEFAULT NULL COMMENT 'Weight in Kg',
  Job VARCHAR(50) DEFAULT NULL,
  Job_Address VARCHAR(150) DEFAULT NULL COMMENT 'Composite attribute',
  Job_Address_Governorate VARCHAR(50) DEFAULT NULL,
  Job_Address_District VARCHAR(50) DEFAULT NULL,
  Job_Address_Building_Number VARCHAR(50) DEFAULT NULL,
  Note TEXT DEFAULT NULL,
  City VARCHAR(50) DEFAULT NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Patient_Id),
  UNIQUE INDEX Patient_Id_UNIQUE(Patient_Id),
  INDEX max_Patient_id_idx(Patient_Id DESC)
)
ENGINE = INNODB,
AUTO_INCREMENT = 23,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `National_Id_Card_UNIQUE` on table `patient`
--
ALTER TABLE patient 
  ADD UNIQUE INDEX National_Id_Card_UNIQUE(National_Id);

--
-- Create index `User_Id_UNIQUE` on table `patient`
--
ALTER TABLE patient 
  ADD UNIQUE INDEX User_Id_UNIQUE(User_Id);

--
-- Create foreign key
--
ALTER TABLE patient 
  ADD CONSTRAINT User_Patient FOREIGN KEY (User_Id)
    REFERENCES user(User_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `old_history`
--
CREATE TABLE old_history (
  Old_History_Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Type INT NOT NULL COMMENT '0 for Disease  ,\\\\n1 for Family Disease ,\\\\n2 for opeartion ,\\\\n3 for Drug ,\\\\n4 for  Vaccine ,\\\\n5 for Lab Test ,\\\\n6 for Radiology Test',
  Name VARCHAR(200) NOT NULL,
  Start_Date DATE NOT NULL,
  End_Date DATE DEFAULT NULL,
  Dose VARCHAR(150) DEFAULT NULL,
  Image_link VARCHAR(2050) DEFAULT NULL,
  Old_Doctor_Name VARCHAR(200) DEFAULT NULL,
  Old_Doctor_Phone_Number VARCHAR(50) NOT NULL,
  Patient_Id INT NOT NULL,
  Disease_Category INT DEFAULT NULL COMMENT 'Ref list for Disease category\\\\n0 Heart disease\\\\n1 Cancer\\\\n2 Chronic lung disease\\\\n3 Stroke\\\\n4 Alzheimer''''s disease\\\\n5 Diabetes\\\\n6 Chronic kIdney disease\\\\n',
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Old_History_Id, Type),
  UNIQUE INDEX Old_History_Id(Old_History_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Old_history_Idx_1` on table `old_history`
--
ALTER TABLE old_history 
  ADD INDEX Old_history_Idx_1(Patient_Id);

--
-- Create index `Patient_Id_Idx` on table `old_history`
--
ALTER TABLE old_history 
  ADD INDEX Patient_Id_Idx(Patient_Id);

--
-- Create foreign key
--
ALTER TABLE old_history 
  ADD CONSTRAINT Old_History_Pat FOREIGN KEY (Patient_Id)
    REFERENCES patient(Patient_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `icu_adm_dc`
--
CREATE TABLE icu_adm_dc (
  ICU_Ticket_Id INT NOT NULL,
  Patient_Id INT NOT NULL,
  ICU_Adm_DateTime TIMESTAMP NOT NULL,
  ICU_DC_DateTime TIMESTAMP NULL DEFAULT NULL,
  Referred_from INT NOT NULL COMMENT '0 for ED ,\\\\n1 for OR ,\\\\n2 for SUrgery room ,\\\\n3 for IMD,\\\\n4 Another hospital',
  Stay_Relative_Full_Name VARCHAR(600) DEFAULT NULL,
  Stay_Relative_First_Name VARCHAR(150) DEFAULT NULL,
  Stay_Relative_Second_Name VARCHAR(150) DEFAULT NULL,
  Stay_Relative_Third_Name VARCHAR(150) DEFAULT NULL,
  Stay_Relative_Last_Name VARCHAR(150) DEFAULT NULL,
  Stay_Relative_phone_Number VARCHAR(50) DEFAULT NULL,
  Stay_Relative_Address VARCHAR(300) DEFAULT NULL COMMENT 'Composite attribute',
  Stay_Relative_Address_Governorate VARCHAR(50) DEFAULT NULL,
  Stay_Relative_Address_District VARCHAR(50) DEFAULT NULL,
  Stay_Relaive_Address_Street VARCHAR(50) DEFAULT NULL,
  Stay_Relative_Address_Building_Number INT DEFAULT NULL,
  DC_Condition VARCHAR(300) NOT NULL,
  Note TEXT DEFAULT NULL,
  Stay_Realtive_City VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ICU_Ticket_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ICU_Adm_DC_Idx_1` on table `icu_adm_dc`
--
ALTER TABLE icu_adm_dc 
  ADD INDEX ICU_Adm_DC_Idx_1(Patient_Id);

--
-- Create foreign key
--
ALTER TABLE icu_adm_dc 
  ADD CONSTRAINT ICU_Adm_Disc_Pat FOREIGN KEY (Patient_Id)
    REFERENCES patient(Patient_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `icu_follow_up_sheet`
--
CREATE TABLE icu_follow_up_sheet (
  ICU_Follow_Up_Sheet_Id INT NOT NULL,
  DateTime_of_measurment_value TIMESTAMP NOT NULL,
  Shift INT NOT NULL COMMENT '0 for Morning ,\\\\n1 for Evenging ,\\\\n2 for Night',
  Temprature INT NOT NULL,
  Heat_rate INT NOT NULL,
  Blood_sugar INT NOT NULL,
  Oxygen_Saturation INT NOT NULL,
  Blood_pressure INT NOT NULL,
  Respiratory_rate INT NOT NULL,
  Urine_Output INT NOT NULL,
  Eye_opening INT NOT NULL COMMENT '4  for Spontaneous ,\\\\n3 for To speech ,\\\\n2 for To Pain ,\\\\n1 for None',
  Verbal_communication_Non_Intubated INT NOT NULL COMMENT '5 for oerineted ,\\\\n4 for Confused converstation,\\\\n3 for Inapropriate words ,\\\\n2 for Incompehensible sound,\\\\n1 for None',
  Verbal_communication_Intubated INT NOT NULL,
  Response INT NOT NULL,
  Consciousness_Score INT NOT NULL COMMENT 'Derived Score',
  Has_Fallen INT NOT NULL COMMENT '25 for yes ,\\\\n0 for No',
  Accompaning_Dias INT NOT NULL COMMENT '15 for Yes ,\\\\n0 for No',
  Tool_AIds INT NOT NULL COMMENT '0 for nevous systems ,\\\\n15 for cane ,\\\\n30 for Wheel chair /Bed lieutenant',
  intravenous_injection INT NOT NULL COMMENT '20 for Yes ,\\\\n0 for No',
  Movment INT NOT NULL COMMENT '20 for Dysfunctional ,\\\\n10 for weak ,\\\\n0 for Normal /No movment /Bed lieutenant',
  Nervous_state INT NOT NULL COMMENT '15 for unaware of the dimensions ,\\\\n0 for aware of the dimensions',
  Morse_Score INT NOT NULL COMMENT 'Derived Score',
  Actions_taken TEXT NOT NULL,
  ICU_Ticket_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (ICU_Follow_Up_Sheet_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ICU_Follow_Up_Sheet_Idx_1` on table `icu_follow_up_sheet`
--
ALTER TABLE icu_follow_up_sheet 
  ADD INDEX ICU_Follow_Up_Sheet_Idx_1(ICU_Ticket_Id);

--
-- Create foreign key
--
ALTER TABLE icu_follow_up_sheet 
  ADD CONSTRAINT ICU_Fol_Up_ICU_Adm_Disc FOREIGN KEY (ICU_Ticket_Id)
    REFERENCES icu_adm_dc(ICU_Ticket_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `icu_relative_visit`
--
CREATE TABLE icu_relative_visit (
  Relative_Name VARCHAR(200) NOT NULL,
  Visit_DateTime TIMESTAMP NOT NULL,
  ICU_Follow_Up_Sheet_Id INT NOT NULL,
  PRIMARY KEY (Relative_Name, Visit_DateTime)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ICU_Relative_Visit_Idx_1` on table `icu_relative_visit`
--
ALTER TABLE icu_relative_visit 
  ADD INDEX ICU_Relative_Visit_Idx_1(ICU_Follow_Up_Sheet_Id);

--
-- Create foreign key
--
ALTER TABLE icu_relative_visit 
  ADD CONSTRAINT Realative_Visit_ICU_Follow_Up_Sheet FOREIGN KEY (ICU_Follow_Up_Sheet_Id)
    REFERENCES icu_follow_up_sheet(ICU_Follow_Up_Sheet_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `er_adm_and_dc`
--
CREATE TABLE er_adm_and_dc (
  Ticket_Id INT NOT NULL AUTO_INCREMENT,
  Patient_Id INT NOT NULL,
  Relative_Full_Name VARCHAR(600) DEFAULT NULL COMMENT 'Composite attribute',
  Relative_First_Name VARCHAR(150) DEFAULT NULL,
  Relative_Second_Name VARCHAR(150) DEFAULT NULL,
  Relative_Third_Name VARCHAR(150) DEFAULT NULL,
  Relative_Last_Name VARCHAR(150) DEFAULT NULL,
  Relative_phone_Number VARCHAR(50) DEFAULT NULL,
  Relative_Address VARCHAR(300) DEFAULT NULL COMMENT 'Composite attribute',
  Relative_Address_Governorate VARCHAR(50) DEFAULT NULL,
  Relative_Address_District VARCHAR(50) DEFAULT NULL,
  Relaive_Address_Street VARCHAR(50) DEFAULT NULL,
  Relative_Address_Building_Number VARCHAR(3) DEFAULT NULL,
  Adm_DateTime TIMESTAMP NOT NULL,
  DC_DateTime TIMESTAMP NULL DEFAULT NULL,
  Stay_Duration DECIMAL(6, 2) DEFAULT NULL COMMENT 'Duration of stay in hours. ',
  Adm_Type INT NOT NULL COMMENT '0 for ED\\\\n1 for Clinics\\\\n2 for Another hospital',
  Fees_Type INT NOT NULL COMMENT '0 for Free\\\\n1 for Full Price\\\\n2 for Med Insurance',
  provisional_Dia TEXT NOT NULL COMMENT 'ED Doctor (Internship Doctor) Dia',
  DC_Patient_Type INT DEFAULT NULL COMMENT '0 for Cured\\\\n1  for Got Better\\\\n2 for DIdn''''t get better\\\\n3 for Died before 48 hours\\\\n4 Died after 48 hours',
  Note TEXT DEFAULT NULL,
  Realtive_City VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Ticket_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Adm_and_DC_Idx_1` on table `er_adm_and_dc`
--
ALTER TABLE er_adm_and_dc 
  ADD INDEX Adm_and_DC_Idx_1(Patient_Id);

--
-- Create foreign key
--
ALTER TABLE er_adm_and_dc 
  ADD CONSTRAINT Adm_Disc_Pat FOREIGN KEY (Patient_Id)
    REFERENCES patient(Patient_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `doctor_call`
--
CREATE TABLE doctor_call (
  Call_Id INT NOT NULL,
  Adm_and_DC_Ticket_Id INT NOT NULL,
  Caller_Doctor_Id INT NOT NULL COMMENT 'The ED Doctor who Call the needed specific Departments Doctor.',
  Responder_Docotor_Id INT NOT NULL,
  Reporting_DateTime TIMESTAMP NOT NULL COMMENT 'Now / Current Time',
  Report_Delivery_DateTime TIMESTAMP NOT NULL,
  Debate_DateTime TIMESTAMP NOT NULL,
  Follow_Up_DateTime TIMESTAMP NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Call_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'This table represents the Doctor Call for a Patient in the ED.\\\\nThe ED Doctor Call specific needed Departments for each Patient after his initial examination.';

--
-- Create index `Doctor_Call_Idx_1` on table `doctor_call`
--
ALTER TABLE doctor_call 
  ADD INDEX Doctor_Call_Idx_1(Adm_and_DC_Ticket_Id);

--
-- Create foreign key
--
ALTER TABLE doctor_call 
  ADD CONSTRAINT Dr_Call_Adm_Disc FOREIGN KEY (Adm_and_DC_Ticket_Id)
    REFERENCES er_adm_and_dc(Ticket_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `authtoken`
--
CREATE TABLE authtoken (
  id INT NOT NULL AUTO_INCREMENT,
  token VARCHAR(255) NOT NULL,
  userId INT NOT NULL,
  expiresAt DATETIME NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `token` on table `authtoken`
--
ALTER TABLE authtoken 
  ADD UNIQUE INDEX token(token);

--
-- Create foreign key
--
ALTER TABLE authtoken 
  ADD CONSTRAINT authtoken_ibfk_1 FOREIGN KEY (userId)
    REFERENCES user(User_Id);

--
-- Create table `doctor`
--
CREATE TABLE doctor (
  Doctor_Id INT NOT NULL,
  National_Id_Card CHAR(15) NOT NULL,
  Full_Name VARCHAR(600) NOT NULL,
  First_Name VARCHAR(150) NOT NULL,
  Second_Name VARCHAR(150) NOT NULL,
  Third_Name VARCHAR(150) NOT NULL,
  Last_Name VARCHAR(150) NOT NULL,
  Degree INT NOT NULL COMMENT 'Ref for Latest Scientific Degree\\\\n0 Bachelor بكالوريوس\\\\n1 Postgraduate Diploma دبلوم الدراسات العليا\\\\n2 Egyptian Associate degree درجة الزمالة المصرية\\\\n3 Fellowship الزمالة\\\\n4 Royal Membership عضوية الكلية الملكية\\\\n5 Master درجة الماجستير\\\\n6 PhD دكتوراه\\\\n',
  Posotion INT NOT NULL COMMENT 'Ref for Position Level in the Department',
  Department_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Doctor_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `icu_doctor_visit`
--
CREATE TABLE icu_doctor_visit (
  Doctor_Visit_Id INT NOT NULL,
  Doctor_Id INT NOT NULL,
  Visit_DateTime TIMESTAMP NOT NULL,
  Visit_Note TEXT NOT NULL,
  ICU_Follow_Up_Sheet_Id INT NOT NULL,
  PRIMARY KEY (Doctor_Visit_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ICU_Doctor_Visit_Idx_1` on table `icu_doctor_visit`
--
ALTER TABLE icu_doctor_visit 
  ADD INDEX ICU_Doctor_Visit_Idx_1(Doctor_Id);

--
-- Create index `ICU_Doctor_Visit_Idx_2` on table `icu_doctor_visit`
--
ALTER TABLE icu_doctor_visit 
  ADD INDEX ICU_Doctor_Visit_Idx_2(ICU_Follow_Up_Sheet_Id);

--
-- Create foreign key
--
ALTER TABLE icu_doctor_visit 
  ADD CONSTRAINT Drs_ICU_Drs_Visit FOREIGN KEY (Doctor_Id)
    REFERENCES doctor(Doctor_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE icu_doctor_visit 
  ADD CONSTRAINT ICU_Drs_Visit_ICU_Fol_Up FOREIGN KEY (ICU_Follow_Up_Sheet_Id)
    REFERENCES icu_follow_up_sheet(ICU_Follow_Up_Sheet_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `emerg_skd`
--
CREATE TABLE emerg_skd (
  Department_Id INT NOT NULL,
  Day_of_the_Week INT NOT NULL COMMENT 'Ref for list of days of the Weeks',
  Seniority_Level INT NOT NULL COMMENT '0 for junior,\\\\n1 for senior,\\\\n2 for Head of Senior',
  Doctor_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Seniority_Level, Day_of_the_Week, Department_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Emerg_Skd_Idx_1` on table `emerg_skd`
--
ALTER TABLE emerg_skd 
  ADD INDEX Emerg_Skd_Idx_1(Doctor_Id);

--
-- Create foreign key
--
ALTER TABLE emerg_skd 
  ADD CONSTRAINT Dr_Emerg_Skd FOREIGN KEY (Doctor_Id)
    REFERENCES doctor(Doctor_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `emerg_skd_call_jct`
--
CREATE TABLE emerg_skd_call_jct (
  Emerg_Skd_Call_JCT_Id INT NOT NULL,
  Doctor_Call_Id INT NOT NULL,
  Emerg_Skd_Seniority_Level INT NOT NULL,
  Emerg_Skd_Day_of_the_Week INT NOT NULL,
  Emerg_Skd_Department_Id INT NOT NULL,
  PRIMARY KEY (Emerg_Skd_Call_JCT_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Emerg_Skd_Call_JCT_Idx_1` on table `emerg_skd_call_jct`
--
ALTER TABLE emerg_skd_call_jct 
  ADD INDEX Emerg_Skd_Call_JCT_Idx_1(Doctor_Call_Id);

--
-- Create index `Emerg_Skd_Call_JCT_Idx_2` on table `emerg_skd_call_jct`
--
ALTER TABLE emerg_skd_call_jct 
  ADD INDEX Emerg_Skd_Call_JCT_Idx_2(Emerg_Skd_Seniority_Level, Emerg_Skd_Day_of_the_Week, Emerg_Skd_Department_Id);

--
-- Create foreign key
--
ALTER TABLE emerg_skd_call_jct 
  ADD CONSTRAINT Call_JCT_Dr_Call FOREIGN KEY (Doctor_Call_Id)
    REFERENCES doctor_call(Call_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE emerg_skd_call_jct 
  ADD CONSTRAINT Emerg_Skd_Junc_Emerg_Skd FOREIGN KEY (Emerg_Skd_Seniority_Level, Emerg_Skd_Day_of_the_Week, Emerg_Skd_Department_Id)
    REFERENCES emerg_skd(Seniority_Level, Day_of_the_Week, Department_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `clinicss_skd`
--
CREATE TABLE clinicss_skd (
  Id INT NOT NULL,
  Start_Time TIME NOT NULL,
  End_Time TIME NOT NULL,
  Day_of_the_Week INT NOT NULL,
  Is_AvaiLable TINYINT(1) NOT NULL,
  Doctor_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Clinicss_Skd_Idx_1` on table `clinicss_skd`
--
ALTER TABLE clinicss_skd 
  ADD INDEX Clinicss_Skd_Idx_1(Doctor_Id);

--
-- Create foreign key
--
ALTER TABLE clinicss_skd 
  ADD CONSTRAINT ClinicssSkdDoctor FOREIGN KEY (Doctor_Id)
    REFERENCES doctor(Doctor_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `patient_appt`
--
CREATE TABLE patient_appt (
  Appt_Id INT NOT NULL AUTO_INCREMENT,
  Date DATE NOT NULL,
  Start_Time TIME NOT NULL,
  End_Time TIME NOT NULL,
  Report TEXT NOT NULL,
  Patient_Id INT NOT NULL,
  Clinicss_Skd_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Appt_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Patient_Appt_Idx_1` on table `patient_appt`
--
ALTER TABLE patient_appt 
  ADD INDEX Patient_Appt_Idx_1(Patient_Id);

--
-- Create index `Patient_Appt_Idx_2` on table `patient_appt`
--
ALTER TABLE patient_appt 
  ADD INDEX Patient_Appt_Idx_2(Clinicss_Skd_Id);

--
-- Create foreign key
--
ALTER TABLE patient_appt 
  ADD CONSTRAINT Patient_Appt_Clinicss_Skd FOREIGN KEY (Clinicss_Skd_Id)
    REFERENCES clinicss_skd(Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE patient_appt 
  ADD CONSTRAINT Patient_Appt_Patient FOREIGN KEY (Patient_Id)
    REFERENCES patient(Patient_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `case_dia`
--
CREATE TABLE case_dia (
  Case_Dia_Id INT NOT NULL,
  Doctor_Id INT NOT NULL,
  Dia_Location INT NOT NULL COMMENT '0 for ED ,\\\\n1 for Ops,\\\\n2 for Clinicss ,\\\\n3 for ICU,\\\\n4 for Ward,\\\\n5 for NICU\\\\n',
  Involved_Department INT NOT NULL,
  Patient_Complaint TEXT NOT NULL,
  Dia TEXT NOT NULL,
  Dia_DateTime TIMESTAMP NOT NULL,
  Clinicsal_examination TEXT NOT NULL,
  Doctor_Call_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  Patient_Appt_Id INT NOT NULL,
  PRIMARY KEY (Case_Dia_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Case summary on the Patient''''s condition written by Doctor.';

--
-- Create index `Case_Dia_Id_UNIQUE` on table `case_dia`
--
ALTER TABLE case_dia 
  ADD UNIQUE INDEX Case_Dia_Id_UNIQUE(Case_Dia_Id);

--
-- Create index `Case_Dia_Idx_1` on table `case_dia`
--
ALTER TABLE case_dia 
  ADD INDEX Case_Dia_Idx_1(Doctor_Call_Id);

--
-- Create index `fk_Case_Dia_Patient_Appt1_Idx` on table `case_dia`
--
ALTER TABLE case_dia 
  ADD INDEX fk_Case_Dia_Patient_Appt1_Idx(Patient_Appt_Id);

--
-- Create foreign key
--
ALTER TABLE case_dia 
  ADD CONSTRAINT Case_Dia_Doctor_Call FOREIGN KEY (Doctor_Call_Id)
    REFERENCES doctor_call(Call_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE case_dia 
  ADD CONSTRAINT Case_Dia_Patient_Appt FOREIGN KEY (Patient_Appt_Id)
    REFERENCES patient_appt(Appt_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `trt_medication`
--
CREATE TABLE trt_medication (
  Medication_Id INT NOT NULL,
  New_Medication VARCHAR(100) NOT NULL,
  Medication_Start_Date DATE NOT NULL,
  Medication_end_Date DATE NOT NULL,
  Special_Instructions VARCHAR(500) NOT NULL,
  Lab_investigation VARCHAR(500) NOT NULL,
  Case_Dia_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Medication_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Trt_Medication_Idx_1` on table `trt_medication`
--
ALTER TABLE trt_medication 
  ADD INDEX Trt_Medication_Idx_1(Case_Dia_Id);

--
-- Create foreign key
--
ALTER TABLE trt_medication 
  ADD CONSTRAINT Trt_Med_Case_Dia FOREIGN KEY (Case_Dia_Id)
    REFERENCES case_dia(Case_Dia_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `radiology_test`
--
CREATE TABLE radiology_test (
  Radiology_test_Id INT NOT NULL,
  Test_Type INT NOT NULL COMMENT 'Ref from a list of avaiLable tests.',
  Result_image_link VARCHAR(2050) NOT NULL,
  Request_test_DateTime TIMESTAMP NOT NULL,
  Recieve_test_DateTime TIMESTAMP NOT NULL,
  Involved_Department_Id INT NOT NULL,
  Case_Dia_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Radiology_test_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Radiology_test_Idx_1` on table `radiology_test`
--
ALTER TABLE radiology_test 
  ADD INDEX Radiology_test_Idx_1(Case_Dia_Id);

--
-- Create foreign key
--
ALTER TABLE radiology_test 
  ADD CONSTRAINT Radiolgy_Test_Case_Dia FOREIGN KEY (Case_Dia_Id)
    REFERENCES case_dia(Case_Dia_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `op`
--
CREATE TABLE op (
  Op_Id INT NOT NULL,
  Op_Name VARCHAR(200) NOT NULL,
  Reasons_for_Op TEXT NOT NULL,
  Involved_Department_Id INT NOT NULL,
  Anaestheric_Doctor_Id INT NOT NULL,
  Sergeon_Id INT NOT NULL,
  First_Doctor_Assistant_Id INT NOT NULL,
  Second_Doctor_Assistance_Id INT DEFAULT NULL,
  First_Nurse_Id INT NOT NULL,
  Second_nurse_Id INT DEFAULT NULL,
  Preparation_nurse_Id INT NOT NULL,
  Anethetic_Used VARCHAR(100) NOT NULL,
  Op_Date DATE NOT NULL,
  Op_Begin_DateTime TIMESTAMP NOT NULL,
  Op_End_DateTime TIMESTAMP NOT NULL,
  Op_Deatils TEXT NOT NULL,
  Op_Result TEXT NOT NULL,
  Op_complications TEXT NOT NULL,
  Patient_Status_After_Op TEXT NOT NULL,
  Case_Dia_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  Op_History_Id INT NOT NULL,
  Location_Department INT NOT NULL,
  PRIMARY KEY (Op_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Op_Idx_1` on table `op`
--
ALTER TABLE op 
  ADD INDEX Op_Idx_1(Case_Dia_Id);

--
-- Create foreign key
--
ALTER TABLE op 
  ADD CONSTRAINT Ope_Case_Dia FOREIGN KEY (Case_Dia_Id)
    REFERENCES case_dia(Case_Dia_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `op_data`
--
CREATE TABLE op_data (
  Op_Data_Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Op_Id INT NOT NULL,
  Doctor_Id INT NOT NULL,
  PRIMARY KEY (Op_Data_Id),
  UNIQUE INDEX Op_Data_Id(Op_Data_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Op_Data_Idx_1` on table `op_data`
--
ALTER TABLE op_data 
  ADD INDEX Op_Data_Idx_1(Op_Id);

--
-- Create index `Op_Data_Idx_2` on table `op_data`
--
ALTER TABLE op_data 
  ADD INDEX Op_Data_Idx_2(Doctor_Id);

--
-- Create foreign key
--
ALTER TABLE op_data 
  ADD CONSTRAINT Op_Data_Op FOREIGN KEY (Op_Id)
    REFERENCES op(Op_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE op_data 
  ADD CONSTRAINT OpDataDoctor FOREIGN KEY (Doctor_Id)
    REFERENCES doctor(Doctor_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `lab_test`
--
CREATE TABLE lab_test (
  Lab_test_Id INT NOT NULL,
  Sample_Type INT NOT NULL COMMENT '0 for EDITA Blood,\\\\n1 for Citrated Blood,\\\\n2 for Serum,\\\\n3 for Urine,\\\\n4 for Biologica fluId\\\\n',
  Lab_worker_Name VARCHAR(150) NOT NULL COMMENT 'Name of the technician who took the sample from the Patient',
  Lap_branch VARCHAR(150) NOT NULL,
  Lap_location VARCHAR(50) NOT NULL,
  Lap_Number INT NOT NULL,
  Result_image_link VARCHAR(2050) NOT NULL,
  Request_sample_DateTime TIMESTAMP NOT NULL COMMENT 'DateTime for taking the sample from the Patient.',
  Recieve_sample_DateTime TIMESTAMP NOT NULL COMMENT 'DateTime for taking the sample from the lap.',
  Involved_Department INT NOT NULL,
  Case_Dia_Id INT NOT NULL,
  Note TEXT DEFAULT NULL,
  PRIMARY KEY (Lab_test_Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Lab_Test_Idx_1` on table `lab_test`
--
ALTER TABLE lab_test 
  ADD INDEX Lab_Test_Idx_1(Case_Dia_Id);

--
-- Create foreign key
--
ALTER TABLE lab_test 
  ADD CONSTRAINT Lab_Test_Case_Dia FOREIGN KEY (Case_Dia_Id)
    REFERENCES case_dia(Case_Dia_Id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `error`
--
CREATE TABLE error (
  id INT NOT NULL AUTO_INCREMENT,
  message VARCHAR(255) NOT NULL,
  status INT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'Ryan', '123456789', 'ryan123@gmail.com', 'patient', '2023-04-29 08:59:46', '2023-04-29 08:59:46'),
(2, 'Maryrose', '123456789', 'Maryrose@gmail.com', 'patient', '2023-04-29 09:10:30', '2023-04-29 09:10:30'),
(3, 'Danae', '123456789', 'Danae@gmail.com', 'patient', '2023-04-29 09:11:23', '2023-04-29 09:11:23'),
(4, 'Kamel', '123456789', 'Kamel@gmail.com', 'patient', '2023-04-29 09:12:01', '2023-04-29 09:12:01'),
(5, 'ahmed', '123456789', 'ahmed1@gmail.com', 'patient', '2023-04-29 09:12:14', '2023-04-29 09:12:14'),
(6, 'Mohamed', '123456789', 'Mohamed1@gmail.com', 'patient', '2023-04-29 09:12:20', '2023-04-29 09:12:20'),
(7, 'ali', '123456789', 'ali1@gmail.com', 'patient', '2023-04-29 09:12:23', '2023-04-29 09:12:23'),
(8, 'Holton', '123456789', 'Holton@gmail.com', 'patient', '2023-04-29 09:12:25', '2023-04-29 09:12:25'),
(9, 'Badieh', '123456789', 'Badieh@gmail.com', 'admin', '2023-04-29 09:12:27', '2023-04-29 09:12:27'),
(10, 'John', '123456789', 'John.lamei.12@gmail.com', 'admin', '2023-04-29 09:12:29', '2023-04-29 09:12:29'),
(11, 'Fathy', '123456789', 'Fathy@gmail.com', 'patient', '2023-04-29 09:12:32', '2023-04-29 09:12:32');

-- 
-- Dumping data for table doctor
--
-- Table hospital_2.doctor does not contain any data (it is empty)

-- 
-- Dumping data for table patient
--
INSERT INTO patient VALUES
(21, 10, '30012090201054', 'John Lamei Shahin Rezaik', 'John', 'Lamei', 'Shahin', 'Rezaik', '2000-12-08', 0, 0, 0, 0, 53, 0, '    ', '', '', '', '', '', '', '', '01029182175', 0.00, 0.00, '', '', '', '', '', '', '', '2023-04-28 11:06:39', '2023-04-29 10:32:17'),
(22, 11, '30012090661122', 'Ahmed Fathy Hagag Abdallah', 'Ahmed', 'Fathy', 'Hagag', 'Abdallah', '2000-05-08', 0, 0, 0, 0, 53, 0, '    ', '', '', '', '', '', '', '', '01029182698', 0.00, 0.00, '', '', '', '', '', '', '', '2023-04-28 15:02:00', '2023-04-29 10:32:17');

-- 
-- Dumping data for table clinicss_skd
--
-- Table hospital_2.clinicss_skd does not contain any data (it is empty)

-- 
-- Dumping data for table er_adm_and_dc
--
-- Table hospital_2.er_adm_and_dc does not contain any data (it is empty)

-- 
-- Dumping data for table patient_appt
--
-- Table hospital_2.patient_appt does not contain any data (it is empty)

-- 
-- Dumping data for table doctor_call
--
-- Table hospital_2.doctor_call does not contain any data (it is empty)

-- 
-- Dumping data for table case_dia
--
-- Table hospital_2.case_dia does not contain any data (it is empty)

-- 
-- Dumping data for table icu_adm_dc
--
-- Table hospital_2.icu_adm_dc does not contain any data (it is empty)

-- 
-- Dumping data for table op
--
-- Table hospital_2.op does not contain any data (it is empty)

-- 
-- Dumping data for table icu_follow_up_sheet
--
-- Table hospital_2.icu_follow_up_sheet does not contain any data (it is empty)

-- 
-- Dumping data for table emerg_skd
--
-- Table hospital_2.emerg_skd does not contain any data (it is empty)

-- 
-- Dumping data for table trt_medication
--
-- Table hospital_2.trt_medication does not contain any data (it is empty)

-- 
-- Dumping data for table token
--
-- Table hospital_2.token does not contain any data (it is empty)

-- 
-- Dumping data for table radiology_test
--
-- Table hospital_2.radiology_test does not contain any data (it is empty)

-- 
-- Dumping data for table op_data
--
-- Table hospital_2.op_data does not contain any data (it is empty)

-- 
-- Dumping data for table old_history
--
-- Table hospital_2.old_history does not contain any data (it is empty)

-- 
-- Dumping data for table lab_test
--
-- Table hospital_2.lab_test does not contain any data (it is empty)

-- 
-- Dumping data for table icu_relative_visit
--
-- Table hospital_2.icu_relative_visit does not contain any data (it is empty)

-- 
-- Dumping data for table icu_doctor_visit
--
-- Table hospital_2.icu_doctor_visit does not contain any data (it is empty)

-- 
-- Dumping data for table error
--
-- Table hospital_2.error does not contain any data (it is empty)

-- 
-- Dumping data for table emerg_skd_call_jct
--
-- Table hospital_2.emerg_skd_call_jct does not contain any data (it is empty)

-- 
-- Dumping data for table authtoken
--
-- Table hospital_2.authtoken does not contain any data (it is empty)

--
-- Set default database
--
USE hospital_2;

--
-- Drop trigger `concat_names_trigger`
--
DROP TRIGGER IF EXISTS concat_names_trigger;

--
-- Drop trigger `concat_Address_trigger`
--
DROP TRIGGER IF EXISTS concat_Address_trigger;

--
-- Set default database
--
USE hospital_2;

DELIMITER $$

--
-- Create trigger `concat_Address_trigger`
--
CREATE 
	DEFINER = 'root'@'localhost'
TRIGGER concat_Address_trigger
	BEFORE INSERT
	ON patient
	FOR EACH ROW
SET NEW.Address = CONCAT(NEW.Governorate, ' ', NEW.City, ' ', NEW.District, ' ', NEW.Street,' ',new.Building_Number)
$$

--
-- Create trigger `concat_names_trigger`
--
CREATE 
	DEFINER = 'root'@'localhost'
TRIGGER concat_names_trigger
	BEFORE INSERT
	ON patient
	FOR EACH ROW
	FOLLOWS concat_Address_trigger
SET NEW.Full_Name = CONCAT(NEW.First_Name, ' ', NEW.Second_Name, ' ', NEW.Third_Name, ' ', NEW.Last_Name)
$$

DELIMITER ;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;